/**
 * Represents a node in the conceptual blend graph.
 */
export interface ConceptNode {
  /** The identifier for the node. */
  id: string;
  /** The label or name of the concept. */
  label: string;
  /** The role this node plays within the blending topology. */
  type: 'input-a' | 'input-b' | 'generic' | 'blend';
  /** The grouping identifier used for visualization clustering. */
  group: number;
  /** The calculated gravitational pull of this node (Symbiotic Tensor Mesh). */
  gravity?: number;
  /** Z-Axis Inference projection to resolve RCC-8 PO contradictions without Euclidean collapse. */
  z?: number;
  /** Boolean indicating if this node occupies a Phantom Dimension for paraconsistent states. */
  phantomDimension?: boolean;
}

/**
 * Represents a relationship or structural mapping between two concept nodes.
 */
export interface ConceptLink {
  /** The identifier of the origin node. */
  source: string;
  /** The identifier of the destination node. */
  target: string;
  /** The strength or weight of the relationship. */
  value: number;
}

/**
 * Encapsulates the topological structure of a conceptual space.
 */
export interface GraphData {
  /** The collection of concept nodes in the graph. */
  nodes: ConceptNode[];
  /** The collection of relational links connecting the nodes. */
  links: ConceptLink[];
}

/**
 * Represents the extracted abstract structural commonalities between two input concepts.
 */
export interface GenericSpaceResult {
  /** A list of shared abstract structures. */
  commonStructure: string[];
  /** A list of structural correspondences between the input spaces. */
  mappings: string[];
  /** A metric from 0-100 indicating the degree of structural alignment. */
  similarityScore: number;
}


/**
 * Represents a deterministic human intervention injected into a probabilistic AI generation.
 * Embodies the Golden Scar Protocol to maintain tension.
 */

/**
 * The five Pluriversal Lenses used to inject deterministic socio-technical dissonance.
 */
export type PluriversalLens = 'Digital_Habitus' | 'Extractive_Sprint' | 'Crip-Time_Genealogy' | 'Relational_Sovereignty' | 'Artifact_Imperfection';

/**
 * Represents the topological mapping of stakeholder dissonance.
 */
export interface StakeholderDissonance {
  lens: PluriversalLens;
  tensionScore: number; // 0-100
  topologicalDerivative?: number; // Calculated by TensorMesh
}

export interface EpistemicOverride {
  /** The deterministic human annotation overriding or challenging the AI artifact. */
  annotation: string;
  /** A metric (0-100) indicating the degree to which contradiction is retained rather than resolved. */
  contradictionRetentionScore: number;
  /** The UNIX epoch timestamp of the intervention. */
  timestamp: number;
}

/**
 * Represents a conceptual artifact generated by blending two input spaces.
 */
export interface BlendedConcept {
  /** The title of the generated conceptual blend. */
  name: string;
  /** A summary of the blended concept. */
  description: string;
  /** An explanation of the mechanics and functional implications of the blend. */
  detailedExplanation: string;
  /** The theoretical justification for why this blend functions. */
  rationale: string;
  /** A metric from 1-100 indicating the divergence of the blend. */
  noveltyScore: number;
  /** Optional user feedback indicating the subjective value of the artifact. */
  userRating?: 'like' | 'dislike';
  /** Optional human intervention mapping an unresolved contradiction onto the artifact. */
  epistemicOverride?: EpistemicOverride;
  /** Stakeholder Dissonance injected via Pluriversal Lenses. */
  stakeholderDissonance?: StakeholderDissonance;
}

/**
 * Encapsulates the output of a Conceptual Blending operation.
 */
export interface BlendResult {
  /** The collection of conceptual artifacts generated. */
  blends: BlendedConcept[];
  /** An explanation of the methodology used to achieve the blend. */
  analysis: string;
}

/**
 * Represents the finite state machine status of the application.
 */
export type AppState = 'idle' | 'analyzing' | 'blending' | 'complete' | 'error';

/**
 * Represents a preserved snapshot of a conceptual blending operation for historical archiving.
 */
export interface HistoryItem {
  /** The identifier for this historical record. */
  id: string;
  /** The UNIX epoch timestamp of when this operation occurred. */
  timestamp: number;
  /** The first input concept used in the blend. */
  conceptA: string;
  /** The second input concept used in the blend. */
  conceptB: string;
  /** The structural commonalities extracted during the operation. */
  genericSpace: GenericSpaceResult;
  /** The resulting artifacts generated from the blend. */
  blendResult: BlendResult;
  /** The methodological focus applied to the blend. */
  blendType: 'composition' | 'completion' | 'elaboration';
  /** Indicates whether this record was explicitly preserved by the user. */
  isManualSave?: boolean;
}

/**
 * PHASE 1: GEOMETRIC COGNITION - Unified Meta-Prompting API
 */

/**
 * Defines the high-level geometric topology of the latent space.
 */
export type SceneTopology = 'hyperbolic_dodecahedron_space' | 'elliptic_manifold' | 'spherical_geometry' | 'riemannian_manifold' | 'euclidean_baseline';

/**
 * Modulators representing abstract geometric concepts in the latent space.
 */
export interface PhantomDimensions {
  /** The degree of Gaussian curvature applied to the latent space. */
  gaussCurvature: number;
  /** The degree of Riemannian curvature applied to the latent space. */
  riemannianCurvature: number;
  /** Parameters defining the shortest path curves (geodesics) on the manifold. */
  geodesicMapping: string;
}

/**
 * Directives that directly influence the underlying mathematical structure of the latent space.
 */
export interface GeometricDirective {
  /** High-level definition of the manifold's topology. */
  topology: SceneTopology;
  /** Granular parameter adjustments to simulate non-Euclidean metrics. */
  phantomDimensions: PhantomDimensions;
}

/**
 * PHASE 2: AGENTIC AUTO-OPTIMIZATION & PROVENANCE
 */

/**
 * Quantitative metrics fed back from the Plausibility Oracle (mocked PBR/ray-tracing validation).
 */
export interface PlausibilityOracleMetrics {
  /** Structural Similarity Index Measure for physical adherence. */
  ssim: number;
  /** Peak Signal-to-Noise Ratio. */
  psnr: number;
  /** Universal Image Quality Index. */
  uiqi: number;
}

/**
 * Tracks the influence of training data samples to quantify bias and enable ethical debiasing.
 */
export interface ProvenanceTrail {
  /** Identifier of the conceptual lineage or training data cluster. */
  lineageId: string;
  /** Quantified influence of this lineage on the current generation (0-1). */
  influenceWeight: number;
  /** Indication of semantic drift divergence. */
  semanticDriftDelta: number;
}

/**
 * PHASE 3: CROSS-MODAL PERCEPTUAL FUSION
 */

/**
 * Parameters for explicitly integrating Multispectral Imaging (MSI) data to target Quantum Dot displays.
 */
export interface MSIParameters {
  /** Configuration for purer monochromatic red light emission. */
  monochromaticRedIntensity: number;
  /** Configuration for purer monochromatic green light emission. */
  monochromaticGreenIntensity: number;
  /** Configuration for purer monochromatic blue light emission. */
  monochromaticBlueIntensity: number;
  /** Target hardware profile for perceptual fidelity optimization. */
  targetHardwareProfile: 'quantum_dot' | 'standard_rgb' | 'hdr10';
}


/**
 * PHASE 11: REFLEXIVE REPAIR LOOP
 */

/**
 * Defines a structural rule that generation outputs must not violate.
 */
export interface SemanticIntegrityConstraint {
  constraintId: string;
  description: string;
  validationLogic: (payload: any) => boolean;
}

/**
 * Structured report generated when System 2 (Deterministic Verifier) detects a constraint violation.
 */
export interface LogicViolationReport {
  timestamp: string;
  violatedConstraintId: string;
  erroneousPayload: any;
  rejectionReason: string;
}

/**
 * A durable record of an unresolved or resolved logic violation, stored to prevent future occurrences via FIPI.
 */
export interface SymbolicScar {
  scar_id: string;
  timestamp: string;
  failure_mode: string;
  module_path: string;
  trauma_context: {
    initial_prompt_vector_id: string;
    erroneous_output: string;
    constraint_violation: string;
  };
  reparation_delta: {
    successful_repair_output: string | null;
    attempts_to_resolution: number;
    failure_utility_loss_tokens: number;
  };
}
