/**
 * Represents a node in the conceptual blend graph.
 */
export interface ConceptNode {
  /** The identifier for the node. */
  id: string;
  /** The label or name of the concept. */
  label: string;
  /** The role this node plays within the blending topology. */
  type: 'input-a' | 'input-b' | 'generic' | 'blend';
  /** The grouping identifier used for visualization clustering. */
  group: number;
  /** The calculated gravitational pull of this node (Symbiotic Tensor Mesh). */
  gravity?: number;
}

/**
 * Represents a relationship or structural mapping between two concept nodes.
 */
export interface ConceptLink {
  /** The identifier of the origin node. */
  source: string;
  /** The identifier of the destination node. */
  target: string;
  /** The strength or weight of the relationship. */
  value: number;
}

/**
 * Encapsulates the topological structure of a conceptual space.
 */
export interface GraphData {
  /** The collection of concept nodes in the graph. */
  nodes: ConceptNode[];
  /** The collection of relational links connecting the nodes. */
  links: ConceptLink[];
}

/**
 * Represents the extracted abstract structural commonalities between two input concepts.
 */
export interface GenericSpaceResult {
  /** A list of shared abstract structures. */
  commonStructure: string[];
  /** A list of structural correspondences between the input spaces. */
  mappings: string[];
  /** A metric from 0-100 indicating the degree of structural alignment. */
  similarityScore: number;
}


/**
 * Represents a deterministic human intervention injected into a probabilistic AI generation.
 * Embodies the Golden Scar Protocol to maintain tension.
 */
export interface EpistemicOverride {
  /** The deterministic human annotation overriding or challenging the AI artifact. */
  annotation: string;
  /** A metric (0-100) indicating the degree to which contradiction is retained rather than resolved. */
  contradictionRetentionScore: number;
  /** The UNIX epoch timestamp of the intervention. */
  timestamp: number;
}

/**
 * Represents a conceptual artifact generated by blending two input spaces.
 */
export interface BlendedConcept {
  /** The title of the generated conceptual blend. */
  name: string;
  /** A summary of the blended concept. */
  description: string;
  /** An explanation of the mechanics and functional implications of the blend. */
  detailedExplanation: string;
  /** The theoretical justification for why this blend functions. */
  rationale: string;
  /** A metric from 1-100 indicating the divergence of the blend. */
  noveltyScore: number;
  /** Optional user feedback indicating the subjective value of the artifact. */
  userRating?: 'like' | 'dislike';
  /** Optional human intervention mapping an unresolved contradiction onto the artifact. */
  epistemicOverride?: EpistemicOverride;
}

/**
 * Encapsulates the output of a Conceptual Blending operation.
 */
export interface BlendResult {
  /** The collection of conceptual artifacts generated. */
  blends: BlendedConcept[];
  /** An explanation of the methodology used to achieve the blend. */
  analysis: string;
}

/**
 * Represents the finite state machine status of the application.
 */
export type AppState = 'idle' | 'analyzing' | 'blending' | 'complete' | 'error';

/**
 * Represents a preserved snapshot of a conceptual blending operation for historical archiving.
 */
export interface HistoryItem {
  /** The identifier for this historical record. */
  id: string;
  /** The UNIX epoch timestamp of when this operation occurred. */
  timestamp: number;
  /** The first input concept used in the blend. */
  conceptA: string;
  /** The second input concept used in the blend. */
  conceptB: string;
  /** The structural commonalities extracted during the operation. */
  genericSpace: GenericSpaceResult;
  /** The resulting artifacts generated from the blend. */
  blendResult: BlendResult;
  /** The methodological focus applied to the blend. */
  blendType: 'composition' | 'completion' | 'elaboration';
  /** Indicates whether this record was explicitly preserved by the user. */
  isManualSave?: boolean;
}
